name: Test

on:
  push:

jobs:

  build:
    name: Test Push
    runs-on: ubuntu-latest
    steps:

    - name: Setup
      id: go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - name: Checkout
      id: setup
      uses: actions/checkout@v2

    - name: Tidy
      run: |
        go mod tidy 
        go mod vendor
    
    - name: Lint
      uses: github/super-linter@v2.0.0
      env:
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_GO: true

    - name: Test
      run: go test -v -count=1 -race ./...
      
    
